### ISSUE TITLE
Bug: Update troubleshooting documentation for nmap command

### ISSUE THREAD

**Issue by DanielxBlack** [markbaaijens/rpmusicserver#140]
This should be the change in README.md
* if there is no response from the ping-command, try:
    nmap 192.168.x.1/24

(background)
This is a minor thing, but I notice that the troubleshooting suggests using nmap:

* if there is no response from the ping-command, try:
  * `nmap 192.168.x.*`
 
This is ideal for the commonly-used bash shell:

$ echo "$SHELL"
/bin/bash
$ nmap 10.0.1.*
Starting Nmap 7.80 ( https://nmap.org ) at 2022-08-30 10:17 CDT
Stats: 0:00:02 elapsed; 0 hosts completed (0 up), 256 undergoing Ping Scan
Ping Scan Timing: About 77.34% done; ETC: 10:17 (0:00:01 remaining)

However, if the user is on a system that uses zsh (such as macOS) they will receive the following error due to how zsh handles the wildcard:

 % echo $SHELL
/bin/zsh
% nmap 10.0.1.*
zsh: no matches found: 10.0.1.*

Proposed solution that works across the board would use CIDR notation, such as:

% nmap 10.0.1.1/24
Starting Nmap 7.92 ( https://nmap.org ) at 2022-08-30 10:20 CDT
Stats: 0:00:00 elapsed; 0 hosts completed (0 up), 256 undergoing Ping Scan
Ping Scan Timing: About 5.86% done; ETC: 10:20 (0:00:16 remaining)

This works across bash and zsh, and falls well in line with Nmap's official documentation: https://nmap.org/book/man-examples.html as shown below:

> nmap -sS -O scanme.nmap.org/24
> 
> Launches a stealth SYN scan against each machine that is up out of the 256 IPs on the /24 sized network where Scanme resides. It also tries to determine what operating system is running on each host that is up and running. This requires root privileges because of the SYN scan and OS detection.

Example of proposed change:

* if there is no response from the ping-command, try:
  * `nmap 192.168.x.1/24`

The documentation command can be further enhanced to include specific ports the service uses, however, this may be more than necessary and I think it can work either way (though specifying the ports could greatly reduce nmap scanning time):

* if there is no response from the ping-command, try:
  * `nmap 192.168.x.1/24 -p 80,9002,9091`

**Comment by markbaaijens** [comment]
Tnx for your comment.

I've done some testing.... nmap 192.168.2.* vs. nmap 192.168.2.1/24. 

The 24-variant is about twice as fast as the starred one, so that is good. But.... on my network, the starred-variant resolves 13 hosts, as de 24-variant only returns 11 hosts, so 2 missing; this is consistent and repeatable. Luckily, the 2 missing hosts on the 24-variant, are not the rpms-servers (I have two of them up-and-running in my network, rpms and rpmsdev). So the 24-variant might be a 'better' command (more to spec), but some hosts are missing, which is not good. So we might do more  research here....

As for your suggestion to specify the port when scanning with nmap.... yes, it is a lot faster but the host which we look for (rpms), does not stand out visibly  (anymore) b/c the large list of open ports from the other hosts (normally a few ports).  So my preference is to use nmap with no ports specified.

Note. Internally, in the API/logic-section, nmap is use the port-specifier to speed up the process.

**Comment by DanielxBlack** [comment]
Thank you.

Considering the consistent results, I think it may be best to leave as-is. (wildcard notation). Functionally, Nmap should still scan the same IP range. I'm thinking the timing difference may have more to do with the scan missing two hosts (shortening overall scan duration), but I'm unsure.

Would you think it's best if I close this issue for now?

**Comment by markbaaijens** [comment]
I've found this: https://nmap.org/book/man-host-discovery.html
"If a single subnet is being scanned (i.e. 192.168.0.0/24) Nmap may only have to send two packets to most hosts"
So I guess you are right: the /24 is faster b/c it uses fewer discovery packets. If a host does not react within the given timeframe, is will be skipped. On the other hand..... hosts which do not react quickly enough, are of no interest for the purpose, discovering a rpms-host. In that case, nmap-usage following spec is a better choice. 

If you delete the port-section (lasr paragraph), the change-spec is complete and can be made part of the code.

**Comment by DanielxBlack** [comment]
Good observation on the discovery packets.

As for the actual change, the only update would be as follows:

* if there is no response from the ping-command, try:
  * `nmap 192.168.x.1/24`

**Comment by markbaaijens** [comment]
I've labelled this issue to be part of v0.9. Thank you for your contribution.

**Comment by DanielxBlack** [comment]
No problem. Thank you for the open communication and for allowing me to contribute.
